name: Lint

on:
  push:
    branches:
      - learn

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install
          yarn add prettier eslint super-linter

      - name: Run Prettier
        run: prettier --check .

      - name: Run ESLint
        run: eslint .

      - name: Run Super Linter
        run: super-linter
