name: Reminder to Review
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  remind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Sleep for 5 minutes
        run: sleep 120

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Hey @geoffreylgv, a friendly reminder to review this PR! 👀"
          token: ${{ secrets.GITHUB_TOKEN }}
