name: Reminder to Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  remind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check for Activity and Send Reminder
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REVIEWER="geoffreylgv"
          
          # Check if the PR has been reviewed or commented on in the last 5 hours
          ACTIVITY=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/commits" \
            | jq '.[0].commit.author.date' -r)
          
          CURRENT_TIME=$(date -u -Iseconds)
          
          if [[ $(date -d"$CURRENT_TIME" +%s) -gt $(date -d"$ACTIVITY" +%s) + 360 ]]; then
            # More than 5 hours have passed with no activity, send a reminder
            BODY="Hey @$REVIEWER! Friendly reminder to review this PR! 👀"
            curl -X POST \
              -H "Authorization: token $TOKEN" \
              -d "{\"body\": \"$BODY\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
